# Generated by Django 5.0.1 on 2024-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='bloodPressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='bodyTemperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='heartRate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='oxygen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='respirationRate',
            field=models.IntegerField(null=True),
        ),
    ]
