# Generated by Django 5.0.1 on 2024-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_file_fileclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='patient',
        ),
        migrations.AddField(
            model_name='project',
            name='doctors',
            field=models.ManyToManyField(to='base.doctor'),
        ),
        migrations.AddField(
            model_name='project',
            name='patients',
            field=models.ManyToManyField(to='base.patient'),
        ),
    ]
