# Generated by Django 5.0.1 on 2024-03-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_project_doctor_remove_project_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='doctors',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='patients',
            new_name='patient',
        ),
    ]
