# Generated by Django 5.0.1 on 2024-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_doctors_project_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='patient',
        ),
        migrations.AddField(
            model_name='project',
            name='doctors',
            field=models.ManyToManyField(related_name='projects', to='base.doctor'),
        ),
        migrations.AddField(
            model_name='project',
            name='patients',
            field=models.ManyToManyField(related_name='projects', to='base.patient'),
        ),
    ]
