# Generated by Django 5.0.1 on 2024-03-25 01:11

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_project_doctor_remove_project_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='base.file'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
