# Generated by Django 5.0.1 on 2024-03-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_patient_address_remove_patient_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='base.file'),
        ),
    ]
